---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="fedora"
    - image="fedora" tag="rawhide"

matrix:
  allow_failures:
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "XeeT1gEWClgQQIqKTg6VrOYAE0yGXpy7FE6SNxVKkZia53XxEfknWXa/NbQVun0TZ4tSPBhL5x9WjCMzmDtCkf6/W6mIFUK0EL3lylIer5Ba3z59Llb7sKEr3XCOft40hOPwPH1zaz99+nkQ2EpzUuJWccv+qIlLcR45t5XhduQu5pRlktLuokvEDkjMT03QNx1HHruNe5dsuCTnUDrdDapxCpWlZQmo+9UilB6bkXOXLTPd1vBLDv2wxb5q9/Pv/uYtC+4IFZHlSGVquhFRLua4hLAQcJjO26Q7dNF4Lq847TT53kyDcxd4445rqJecIosm+NHTmR/AHYx37QTUAQKcP9b52u7em5PiioYoaAFVKs2YvZRZJhlJjDbtm4ddFHwwTGyTnb8LrEBgbNQiEgm7C4YtwSDZ5Pd6/u4BzwchjmplmxmOTDzpJ/sUpif/JNURUgonKJjpdL75TKLO/SNYw6EluYIaYZ6eRgnrgUiKm7dF4OJ+aAW4BeofFKRPnPoOX1qHw3lHiamRJAVVgMMEe5mzcah4T1G2csd+GlAaDs8GmbFLHRRVuDOQ8a8JK8l7vPniMjS3BADVt9ljTVkSr5GHz6JSa7vWb7VdmHLCfP/1C/DhzJAdWsEWH7+Nmh2lJJjRjnA4yyB4kJ2rsurirrX/DrcIJ2y/xpr5hKM="
  email: false
