---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: cloud9-fedora-latest
    image: fedora:latest
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        locale_ignore_docker: no
        service_ignore_docker: no
        cloud9_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: fedora-latest
verifier:
  name: goss
  lint:
    name: yamllint
