---
# handlers file for cloud9
- name: place installed marker
  file:
    path: "{{ cloud9_installer }}/installed"
    state: touch

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  notify:
    - restart cloud9

- name: restart cloud9
  service:
    name: cloud9
    state: restarted
